export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_OFFERS = 'SET_OFFERS';
export const OFFERS_FAIL = 'OFFERS_FAIL';
export const ORDER_FAILS = 'ORDER_FAILS';
export const ADD_OFFER = 'ADD_OFFER';
export const REMOVE_OFFER = 'REMOVE_OFFER';
export const OFFERS_START = 'OFFERS_START';
export const UPDATE_OFFERS = 'UPDATE_OFFERS';
export const SET_CART_OFFERS = 'SET_CART_OFFERS';
export const CLEAR_CART_OFFERS = 'CLEAR_CART_OFFERS';
export const INCREASE_CART_OFFER = 'INCREASE_CART_OFFER';
export const DECREASE_CART_OFFER = 'DECREASE_CART_OFFER';
export const REMOVE_CART_OFFER = 'REMOVE_CART_OFFER';
export const SET_IMPOSSIBLE_ORDER_MESSAGE = 'SET_IMPOSSIBLE_ORDER_MESSAGE';
